### ISSUE TITLE
求问有计划增加非直播内容的计划吗

### ISSUE THREAD

**Issue by wizardmanxxx** [muedsa/BilibiliLiveTV#20]
云视听实在被阉割太狠，另一个第三方版本未开源且不再维护了，无倍速等功能
望大佬拯救于水火

**Comment by muedsa** [comment]
不会去支持其他内容了,本身也不太会开发安卓。我目前也是用的那个APP。

**Comment by HolyLow** [comment]
今天是个悲伤的日子，bilibili tv第三方版本对于新视频（大约是202211以后上传的视频）仅能使用360p的高糊清晰度。相信大家对bilibili tv的使用需求都很高，我本人也没咋写过安卓app，但感觉是个很有意思的事情。楼主考虑开这个坑吗，我可以帮忙

**Comment by drw2005** [comment]
第三方bilibili tv已经废了，楼主能否考虑一下接手，大家一起出力。

**Comment by eightsheep67** [comment]
大佬好像开始动了！

**Comment by muedsa** [comment]
预览版, 暂时还没有字幕

**Comment by wizardmanxxx** [comment]
大佬有考虑写个详细版readme嘛，同程序员但没搞过安卓开发，也许可以学习一下贡献下代码

**Comment by llrice** [comment]
看了一下，大佬现在进行中的代码已经可以实现搜索BV号跳转到视频详情页面并选择清晰度进行播放了。但还是有跟以前的第三方bilibili tv遇到了同样的问题，最高只有480P的清晰度。测试了一下，如果使用浏览器访问那么返回的信息中是有更高清晰度的。如果有谁知道能如何绕过这个限制，或者哪怕这个限制实现的原理，大家一起交流一下应该会很有帮助。

**Comment by muedsa** [comment]
需要登录才会有更高清晰度

**Comment by llrice** [comment]
卧槽，大佬牛逼！！！！臭不要脸的催更一下弹幕功能。。。
