### ISSUE TITLE
Bug反馈：视频播放时进度条冻结无法操作

### ISSUE THREAD

**Issue by wjz2001** [muedsa/BilibiliLiveTV#34]
该问题随机出现，暂时未发现规律。就是播放视频时进度条不动，但视频仍然正常播放，此时进度条不会自动隐藏，快进快退从进度条显示的时间开始而非视频当前位置。

**Comment by muedsa** [comment]
使用了默认的Leanback播放器控制条。在播放器控制界面, 选择进度条按OK键或直接使用左右键会进入进度调节模式(会隐藏其他控件)。根据你描述可能是进入了这个模式。
